application: cloud-vision-slackbot
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /tasks/.*
  script: tasks.handler
  login: admin

- url: .*
  script: main.handler

libraries:
- name: endpoints
  version: 1.0

- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

- name: PIL
  version: latest

- name: ssl
  version: latest

- name: pycrypto
  version: latest